package com.example.trueline_listener.ui

object IndianCitiesData {
    val cities = listOf(
        "Mumbai, Maharashtra",
        "Delhi, Delhi",
        "Bengaluru, Karnataka",
        "Hyderabad, Telangana",
        "Ahmedabad, Gujarat",
        "Chennai, Tamil Nadu",
        "Kolkata, West Bengal",
        "Surat, Gujarat",
        "Pune, Maharashtra",
        "Jaipur, Rajasthan",
        "Lucknow, Uttar Pradesh",
        "Kanpur, Uttar Pradesh",
        "Nagpur, Maharashtra",
        "Indore, Madhya Pradesh",
        "Thane, Maharashtra",
        "Bhopal, Madhya Pradesh",
        "Visakhapatnam, Andhra Pradesh",
        "Pimpri-Chinchwad, Maharashtra",
        "Patna, Bihar",
        "Vadodara, Gujarat",
        "Ghaziabad, Uttar Pradesh",
        "Ludhiana, Punjab",
        "Agra, Uttar Pradesh",
        "Nashik, Maharashtra",
        "Faridabad, Haryana",
        "Meerut, Uttar Pradesh",
        "Rajkot, Gujarat",
        "Kalyan-Dombivli, Maharashtra",
        "Vasai-Virar, Maharashtra",
        "Varanasi, Uttar Pradesh",
        "Srinagar, Jammu and Kashmir",
        "Aurangabad, Maharashtra",
        "Dhanbad, Jharkhand",
        "Amritsar, Punjab",
        "Navi Mumbai, Maharashtra",
        "Allahabad (Prayagraj), Uttar Pradesh",
        "Ranchi, Jharkhand",
        "Howrah, West Bengal",
        "Coimbatore, Tamil Nadu",
        "Jabalpur, Madhya Pradesh",
        "Gwalior, Madhya Pradesh",
        "Vijayawada, Andhra Pradesh",
        "Jodhpur, Rajasthan",
        "Madurai, Tamil Nadu",
        "Raipur, Chhattisgarh",
        "Kota, Rajasthan",
        "Guwahati, Assam",
        "Chandigarh, Chandigarh",
        "Solapur, Maharashtra",
        "Hubli-Dharwad, Karnataka",
        "Bareilly, Uttar Pradesh",
        "Moradabad, Uttar Pradesh",
        "Mysore (Mysuru), Karnataka",
        "Gurgaon (Gurugram), Haryana",
        "Aligarh, Uttar Pradesh",
        "Jalandhar, Punjab",
        "Tiruchirappalli, Tamil Nadu",
        "Bhubaneswar, Odisha",
        "Salem, Tamil Nadu",
        "Warangal, Telangana",
        "Mira-Bhayandar, Maharashtra",
        "Thiruvananthapuram, Kerala",
        "Bhiwandi, Maharashtra",
        "Saharanpur, Uttar Pradesh",
        "Guntur, Andhra Pradesh",
        "Amravati, Maharashtra",
        "Bikaner, Rajasthan",
        "Noida, Uttar Pradesh",
        "Jamshedpur, Jharkhand",
        "Bhilai, Chhattisgarh",
        "Cuttack, Odisha",
        "Firozabad, Uttar Pradesh",
        "Kochi, Kerala",
        "Nellore, Andhra Pradesh",
        "Bhavnagar, Gujarat",
        "Dehradun, Uttarakhand",
        "Durgapur, West Bengal",
        "Asansol, West Bengal",
        "Rourkela, Odisha",
        "Nanded, Maharashtra",
        "Kolhapur, Maharashtra",
        "Ajmer, Rajasthan",
        "Akola, Maharashtra",
        "Gulbarga (Kalaburagi), Karnataka",
        "Jamnagar, Gujarat",
        "Ujjain, Madhya Pradesh",
        "Loni, Uttar Pradesh",
        "Siliguri, West Bengal",
        "Jhansi, Uttar Pradesh",
        "Ulhasnagar, Maharashtra",
        "Jammu, Jammu and Kashmir",
        "Sangli-Miraj & Kupwad, Maharashtra",
        "Mangalore, Karnataka",
        "Erode, Tamil Nadu",
        "Belgaum (Belagavi), Karnataka",
        "Ambattur, Tamil Nadu",
        "Tirunelveli, Tamil Nadu",
        "Malegaon, Maharashtra",
        "Gaya, Bihar",
        "Jalgaon, Maharashtra",
        "Udaipur, Rajasthan",
        "Maheshtala, West Bengal",
        "Davanagere, Karnataka",
        "Kozhikode, Kerala",
        "Kurnool, Andhra Pradesh",
        "Rajpur Sonarpur, West Bengal",
        "Rajahmundry, Andhra Pradesh",
        "Bokaro, Jharkhand",
        "South Dumdum, West Bengal",
        "Bellary (Ballari), Karnataka",
        "Patiala, Punjab",
        "Gopalpur, West Bengal",
        "Agartala, Tripura",
        "Bhagalpur, Bihar",
        "Muzaffarnagar, Uttar Pradesh",
        "Bhatpara, West Bengal",
        "Panihati, West Bengal",
        "Latur, Maharashtra",
        "Dhule, Maharashtra",
        "Rohtak, Haryana",
        "Korba, Chhattisgarh",
        "Bhilwara, Rajasthan",
        "Brahmapur, Odisha",
        "Muzaffarpur, Bihar",
        "Ahmednagar, Maharashtra",
        "Mathura, Uttar Pradesh",
        "Kollam, Kerala",
        "Avadi, Tamil Nadu",
        "Kadapa, Andhra Pradesh",
        "Kamarhati, West Bengal",
        "Sambalpur, Odisha",
        "Bilaspur, Chhattisgarh",
        "Shahjahanpur, Uttar Pradesh",
        "Satara, Maharashtra",
        "Bijapur, Karnataka",
        "Rampur, Uttar Pradesh",
        "Shimoga (Shivamogga), Karnataka",
        "Chandrapur, Maharashtra",
        "Junagadh, Gujarat",
        "Thrissur, Kerala",
        "Alwar, Rajasthan",
        "Bardhaman, West Bengal",
        "Kulti, West Bengal",
        "Kakinada, Andhra Pradesh",
        "Nizamabad, Telangana",
        "Parbhani, Maharashtra",
        "Tumkur, Karnataka",
        "Khammam, Telangana",
        "Ozhukarai, Puducherry",
        "Bihar Sharif, Bihar",
        "Panipat, Haryana",
        "Darbhanga, Bihar",
        "Bally, West Bengal",
        "Aizawl, Mizoram",
        "Dewas, Madhya Pradesh",
        "Ichalkaranji, Maharashtra",
        "Karnal, Haryana",
        "Bathinda, Punjab",
        "Jalna, Maharashtra",
        "Eluru, Andhra Pradesh",
        "Barasat, West Bengal",
        "Kirari Suleman Nagar, Delhi",
        "Purnia, Bihar",
        "Satna, Madhya Pradesh",
        "Mau, Uttar Pradesh",
        "Sonipat, Haryana",
        "Farrukhabad, Uttar Pradesh",
        "Sagar, Madhya Pradesh",
        "Rourkela, Odisha",
        "Durg, Chhattisgarh",
        "Imphal, Manipur",
        "Ratlam, Madhya Pradesh",
        "Hapur, Uttar Pradesh",
        "Arrah, Bihar",
        "Karimnagar, Telangana",
        "Anantapur, Andhra Pradesh",
        "Etawah, Uttar Pradesh",
        "Ambernath, Maharashtra",
        "North Dumdum, West Bengal",
        "Bharatpur, Rajasthan",
        "Begusarai, Bihar",
        "New Delhi, Delhi",
        "Gandhinagar, Gujarat",
        "Baranagar, West Bengal",
        "Tiruvottiyur, Tamil Nadu",
        "Puducherry, Puducherry",
        "Sikar, Rajasthan",
        "Thoothukudi, Tamil Nadu",
        "Rewa, Madhya Pradesh",
        "Mirzapur, Uttar Pradesh",
        "Raichur, Karnataka",
        "Pali, Rajasthan",
        "Ramagundam, Telangana",
        "Haridwar, Uttarakhand",
        "Vijayanagaram, Andhra Pradesh",
        "Katihar, Bihar",
        "Nagarcoil, Tamil Nadu",
        "Sri Ganganagar, Rajasthan",
        "Karawal Nagar, Delhi",
        "Mango, Jharkhand",
        "Thanjavur, Tamil Nadu",
        "Bulandshahr, Uttar Pradesh",
        "Uluberia, West Bengal",
        "Murwara, Madhya Pradesh",
        "Sambhal, Uttar Pradesh",
        "Singrauli, Madhya Pradesh",
        "Nadiad, Gujarat",
        "Secunderabad, Telangana",
        "Naihati, West Bengal",
        "Yamunanagar, Haryana",
        "Bidhannagar, West Bengal",
        "Pallavaram, Tamil Nadu",
        "Bidar, Karnataka",
        "Munger, Bihar",
        "Panchkula, Haryana",
        "Burhanpur, Madhya Pradesh",
        "Raurkela Industrial Township, Odisha",
        "Kharagpur, West Bengal",
        "Dindigul, Tamil Nadu",
        "Gandhidham, Gujarat",
        "Hospet, Karnataka",
        "Nangloi Jat, Delhi",
        "Malda, West Bengal",
        "Ongole, Andhra Pradesh",
        "Deoghar, Jharkhand",
        "Chapra, Bihar",
        "Puri, Odisha",
        "Haldia, West Bengal",
        "Khandwa, Madhya Pradesh",
        "Nandyal, Andhra Pradesh",
        "Chittoor, Andhra Pradesh",
        "Morena, Madhya Pradesh",
        "Amroha, Uttar Pradesh",
        "Anand, Gujarat",
        "Bhind, Madhya Pradesh",
        "Bhalswa Jahangir Pur, Delhi",
        "Madhyamgram, West Bengal",
        "Bhiwani, Haryana",
        "Navsari, Gujarat",
        "Bahraich, Uttar Pradesh",
        "Raebareli, Uttar Pradesh",
        "Khammam, Telangana",
        "Maunath Bhanjan, Uttar Pradesh"
    )
}
